apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-kunde-selvregistrering-frontend
  labels:
    app.kubernetes.io/name: fint-kunde-selvregistrering-frontend
    app.kubernetes.io/instance: fint-kunde-selvregistrering-frontend
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-kunde-selvregistrering-frontend:latest
  env:
    - name: BASE_PATH
      value: /
  url:
    hostname: registrering.felleskomponent.no
  ingress:
    enabled: true
    middlewares:
      - fint-kunde-selvregistrering-sso
  resources:
    limits:
      memory: "512Mi"
      cpu: "500m"
    requests:
      memory: "256Mi"
      cpu: "250m"
  restartPolicy: Always