apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fintlabs-no
resources:
  - ../../../base
patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-kunde-selvregistrering-frontend_fintlabs_no"
      - op: replace
        path: "/spec/orgId"
        value: "fintlabs.no"
    target:
      kind: Application
      name: fint-kunde-selvregistrering-frontend
